[workspace]
members = [
  "./crates/backend",
  "./crates/build",
  "./crates/macro",
  "./crates/napi",
  "./crates/sys",
  "./examples/napi",
  "./examples/napi-compat-mode",
  "./bench",
  "./memory-testing",
]

exclude = [
  "./testing"
]

[profile.release]
lto = true
