[package]
description = "Codegen backend for napi procedural macro"
edition = "2018"
homepage = "https://napi.rs"
license = "MIT"
name = "napi-derive-backend"
readme = "README.md"
repository = "https://github.com/napi-rs/napi-rs"
version = "1.0.1"

[features]
strict = []
type-def = ["regex", "once_cell"]

[dependencies]
convert_case = "0.4"
proc-macro2 = "1"
quote = "1"
syn = {version = "1", features = ["fold", "full", "extra-traits"]}

[dependencies.regex]
optional = true
version = "1"

[dependencies.once_cell]
optional = true
version = "1"

[package.metadata.workspaces]
independent = true
