[package]
authors = ["LongYinan <lynweklm@gmail.com>", "Forehalo <forehalo@gmail.com>"]
description = "N-API procedural macros"
edition = "2018"
keywords = ["NodeJS", "FFI", "NAPI", "n-api"]
license = "MIT"
name = "napi-derive"
readme = "README.md"
repository = "https://github.com/napi-rs/napi-rs"
version = "2.0.0-beta.2"

[features]
compat-mode = []
default = ["compat-mode", "full"]
full = ["type-def", "strict"]
strict = ["napi-derive-backend/strict"]
type-def = ["napi-derive-backend/type-def"]

[dependencies]
convert_case = "0.4"
napi-derive-backend = {version = "1.0.14", path = "../backend"}
proc-macro2 = "1.0"
quote = "1.0"
syn = {version = "1.0", features = ["fold", "full", "extra-traits"]}

[lib]
proc-macro = true

[package.metadata.workspaces]
independent = true
