[package]
authors = ["LongYinan <lynweklm@gmail.com>", "Forehalo <forehalo@gmail.com>"]
description = "N-API procedural macros"
edition = "2021"
keywords = ["NodeJS", "FFI", "NAPI", "n-api"]
license = "MIT"
name = "napi-derive"
readme = "README.md"
repository = "https://github.com/napi-rs/napi-rs"
rust-version = "1.65"
version = "2.14.2"

[package.metadata.workspaces]
independent = true

[features]
compat-mode = []
default = ["compat-mode", "full"]
full = ["type-def", "strict"]
noop = ["napi-derive-backend/noop"]
strict = ["napi-derive-backend/strict"]
type-def = ["napi-derive-backend/type-def"]

[dependencies]
convert_case = "0.6"
napi-derive-backend = { version = "1.0.55", path = "../backend" }
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0.61", features = ["fold", "full", "extra-traits"] }
cfg-if = "1.0"

[lib]
proc-macro = true
