name: Windows i686

env:
  DEBUG: 'napi:*'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_test:
    name: stable - windows-latest - i686 - node@16
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
          architecture: 'x64'
          cache: yarn

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: .yarn/cache
          key: npm-cache-windows-i686-msvc-node@16

      - name: 'Install dependencies'
        run: |
          yarn install --mode=skip-build --immutable

      - name: Install
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: i686-pc-windows-msvc

      - name: Cache cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: stable-windows-i686-node@16-cargo-cache

      - name: Check build
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all --bins --examples --tests --target i686-pc-windows-msvc -vvv

      - name: Build
        run: |
          yarn build
          yarn workspace compat-mode-examples build-i686 --release
          yarn workspace examples build-i686 --release

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
          architecture: 'x86'

      - name: Build Tests
        run: |
          yarn test --verbose
          node ./node_modules/electron/install.js
          yarn test:electron
        env:
          RUST_BACKTRACE: 1
